version: 1
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    # GoReleaser will automatically replace these variables for each build
    binary: sops-cli-{{ .Os }}-{{ .Arch }}

# Automatically generates a clean changelog based on your git commits
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'